Set-ItemProperty -Path "$env:fnv_path\Data\FalloutNV.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\DeadMoney.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\HonestHearts.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\OldWorldBlues.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\LonesomeRoad.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\GunRunnersArsenal.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\ClassicPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\MercenaryPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\TribalPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\CaravanPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\YUP RUS - Base Game + All DLC.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\WMIMNV.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Unofficial Patch NVSE Plus.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\YUP RUS - NPC Fixes (Base Game + All DLC).esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\LootMenu.esp" -Name LastWriteTimeUTC -Value (Get-Date)
