Set-ItemProperty -Path "$env:fnv_path\Data\FalloutNV.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\DeadMoney.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\HonestHearts.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\OldWorldBlues.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\LonesomeRoad.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\GunRunnersArsenal.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\ClassicPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\MercenaryPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\TribalPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\CaravanPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Simple Open Strip.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Simple Open Freeside.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\YUP RUS - Base Game + All DLC.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\ISControl.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\WMIMNV.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Unofficial Patch NVSE Plus.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\YUP RUS - NPC Fixes (Base Game + All DLC).esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Delay DLC - DM + HH + OWB + LR + GRA.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\RPM - Remove Pre-order Messages.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Faster Start Menu.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Diagonal movement.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Casino Exchange All.esp" -Name LastWriteTimeUTC -Value (Get-Date)
