Set-ItemProperty -Path "$env:fnv_path\Data\FalloutNV.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\DeadMoney.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\HonestHearts.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\OldWorldBlues.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\LonesomeRoad.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\GunRunnersArsenal.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\ClassicPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\MercenaryPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\TribalPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\CaravanPack.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\YUP RUS - Base Game + All DLC.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\ISControl.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Simple Open Freeside.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Simple Open Strip.esm" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Sierra Madre.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\WMIMNV.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Unofficial Patch NVSE Plus.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\YUP RUS - NPC Fixes (Base Game + All DLC).esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\JSawyer Ultimate.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\DNWeathers.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Casino Exchange All.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\HTRP-Daily Vendor Restock.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\HTRP-Vendor Supply Refresh.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Simple DLC Delay.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\JustHitMarker.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Diagonal movement.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\dD - Enhanced Blood Main NV.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\JustLootMenu.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Vanilla UI Plus.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\The Mod Configuration Menu.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Titans of The New West.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Titans of the New West Icons.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Glove_be_gone.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\Lucky 38 Lights Redone.esp" -Name LastWriteTimeUTC -Value (Get-Date)
Set-ItemProperty -Path "$env:fnv_path\Data\B42Inertia.esp" -Name LastWriteTimeUTC -Value (Get-Date)
